version: '3.8'

services:

    db:
        image: mariadb:10.6.11
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: db
        volumes:
            - ./docker/db:/docker-entrypoint-initdb.d/:ro
